import type { Metadata } from "next";
import { Teko } from "next/font/google";
import "./globals.css";

import { Provider } from "./components/Provider/Provider";

const teko = Teko({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={teko.className}>
        <Provider>
          {children}
        </Provider>

      </body>
    </html>
  );
}
